spring.application.name=SecurityKeycloak

server.port=8087

# Activation de la console web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration de la connexion JDBC (Base en mémoire)
spring.datasource.url=jdbc:h2:mem:securiteKeycloak
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=abdelhafid
spring.datasource.password=K130309980

# Configuration de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# keycloak


# 2. URL de l'émetteur (Issuer) - Remplacez 'votre-realm' par le nom de votre Realm Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/votre-realm

# 3. URL pour récupérer les clés publiques de vérification des jetons (JWK Set URI)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/votre-realm/protocol/openid-connect/certs


